export const SUBMIT_QUERY = 'SUBMIT_QUERY';
export const REQUEST_QUERY = 'REQUEST_QUERY';
export const RECEIVE_QUERY = 'RECEIVE_QUERY';
export const UPDATE_QUERY_PAGINATION = 'UPDATE_QUERY_PAGINATION';

export const SET_ROOT_ENTITY = 'SET_ROOT_ENTITY';
export const ADD_ENTITY_WATCH = 'ADD_ENTITY_WATCH';
export const FETCH_ENTITY = 'FETCH_ENTITY';
export const FETCH_ENTITIES = 'FETCH_ENTITIES';
export const RECEIVE_ENTITY = 'RECEIVE_ENTITY';

export const SHOW_NOTIFY = 'SHOW_NOTIFY';