export const CHANGE_QUERY = 'CHANGE_QUERY';
export const SUBMIT_QUERY = 'SUBMIT_QUERY';
export const FETCH_QUERY = 'FETCH_QUERY';
export const RECEIVE_QUERY = 'RECEIVE_QUERY';
export const FETCH_ENTITY = 'FETCH_ENTITY';
export const RECEIVE_ENTITY = 'RECEIVE_ENTITY';
export const SHOW_NOTIFY = 'SHOW_NOTIFY';