package util

// REST API constants
const (
	Metadata          = "metadata"
	UID               = "uid"
	Name              = "name"
	ResourceID        = "resourceid"
	ObjType           = "objtype"
	Objects           = "objects"
	K8sObj            = "k8sobj"
	Cluster           = "cluster"
	Namespace         = "namespace"
	Many              = "many"
	Relationship      = "relationship"
	JSON              = "json"
	Pod               = "pod"
	Deployment        = "deployment"
	Ingress           = "ingress"
	ReplicaSet        = "replicaset"
	Service           = "service"
	StatefulSet       = "statefulset"
	Owner             = "owner"
	OwnerType         = "ownertype"
	ResourceVersion   = "resourceversion"
	Node              = "node"
	Application       = "application"
	ClusterName       = "clustername"
	Labels            = "labels"
	CreationTime      = "creationtime"
	NumReplicas       = "numreplicas"
	AvailableReplicas = "availablereplicas"
	Strategy          = "strategy"
	DefaultBackend    = "defaultbackend"
	TSL               = "tsl"
	Rules             = "rules"
	Phase             = "phase"
	NodeName          = "nodename"
	IP                = "ip"
	Containers        = "containers"
	Volumes           = "volumes"
	PodSpec           = "podspec"
	Ports             = "ports"
	ServiceType       = "servicetype"
	ClusterIP         = "clusterip"
	Selector          = "selector"
	App               = "app"
	K8sApp            = "k8s-app"
	Fields            = "fields"
	FieldName         = "fieldname"
	FieldType         = "fieldtype"
	Mandatory         = "mandatory"
	Cardinality       = "cardinality"
	One               = "one"
	Query             = "query"
	StartTime         = "starttime"
	Count             = "count"
)
